######################## default configuration ####################
baseURL = "https://oakmtg.club"
title = "Oakmtg (Appreciation) Club | Appreciating Oakland City Meetings"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

[[params.seoTags]]
name = "city"
content = "oakland"



############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
#[[params.plugins.js]]
#link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
weight = 1
hasChildren = true

    [[menu.main]]
    name = "About Us"
    URL = "about"
    parent = "About"
    weight = 1

    [[menu.main]]
    parent = "About"
    name = "methodology"
    URL = "methodology"
    weight = 2

[[menu.main]]
name = "Voter Guide"
weight = 2
hasChildren = true
 
    [[menu.main]]
    name = "How to Vote"
    URL = "how-to-vote"
    parent = "Voter Guide"
    weight = 1

    [[menu.main]]
    name = "Candidates"
    URL = "candidates"
    parent = "Voter Guide"
    weight = 2

    [[menu.main]]
    name = "Ballot Measures"
    weight = 3
    hasChildren = true
    parent = "Voter Guide"


[[menu.main]]
name = "Previous Guides"
weight = 3
hasChildren = true

    [[menu.main]]
    name = "2020 Voter Guide"
    URL = "2020/guide"
    weight = 9
    hasChildren = true
    parent = "Previous Guides"
        
       # [[menu.main]]
       # name = "Home"
       # URL = "2020/guide"
       # parent = "2020 Voter Guide"
       # weight = 2

       # [[menu.main]]
       # name = "2020 District 1"
       # URL = "2020/guide/district-1"
       # parent = "2020 Voter Guide"
       # weight = 3

       # [[menu.main]]
       # name = "2020 District 2"
       # URL = "2020/guide/district-2"
       # parent = "2020 Voter Guide"
       # weight = 4

       # [[menu.main]]
       # name = "2020 District 3"
       # URL = "2020/guide/district-3"
       # parent = "2020 Voter Guide"
       # weight = 5

       # [[menu.main]]
       # name = "2020 District 4"
       # URL = "2020/guide/district-4"
       # parent = "2020 Voter Guide"
       # weight = 6

       # [[menu.main]]
       # name = "2020 District 5"
       # URL = "2020/guide/district-5"
       # parent = "2020 Voter Guide"
       # weight = 7

       # [[menu.main]]
       # name = "2020 District 6"
       # URL = "2020/guide/district-6"
       # parent = "2020 Voter Guide"
       # weight = 8

       # [[menu.main]]
       # name = "2020 District 7"
       # URL = "2020/guide/district-7"
       # parent = "2020 Voter Guide"
       # weight = 9

       # [[menu.main]]
       # name = "2020 How to Vote"
       # URL = "2020/how-to-vote"
       # parent = "2020 Voter Guide"
       # weight = 1

       # [[menu.main]]
       # name = "2020 Candidates"
       # URL = "2020/candidates"
       # parent = "2020 Voter Guide"
       # weight = 2

       # [[menu.main]]
       # name = "2020 Ballot Measures"
       # weight = 3
       # hasChildren = true
       # parent = "2020 Voter Guide"

       #     [[menu.main]]
       #     name = "Home"
       #     URL = "2020/ballot-measures"
       #     parent = "2020 Ballot Measures"
       #     weight = 2

       #     [[menu.main]]
       #     name = "QQ"
       #     URL = "2020/ballot-measures/qq"
       #     parent = "2020 Ballot Measures"
       #     weight = 3

       #     [[menu.main]]
       #     name = "RR"
       #     URL = "2020/ballot-measures/rr"
       #     parent = "2020 Ballot Measures"
       #     weight = 4

       #     [[menu.main]]
       #     name = "S1"
       #     URL = "2020/ballot-measures/s1"
       #     parent = "2020 Ballot Measures"
       #     weight = 5

       #     [[menu.main]]
       #     name = "V"
       #     URL = "2020/ballot-measures/v"
       #     parent = "2020 Ballot Measures"
       #     weight = 6

       #     [[menu.main]]
       #     name = "W"
       #     URL = "2020/ballot-measures/w"
       #     parent = "2020 Ballot Measures"
       #     weight = 7

       #     [[menu.main]]
       #     name = "X"
       #     URL = "2020/ballot-measures/x"
       #     parent = "2020 Ballot Measures"
       #     weight = 8

       #     [[menu.main]]
       #     name = "Y"
       #     URL = "2020/ballot-measures/y"
       #     parent = "2020 Ballot Measures"
       #     weight = 9

#[[menu.main]]
#name = "Call to Action"
#weight = 10
#hasChildren = true
#
#    [[menu.main]]
#    parent = "Call to Action"
#    name = "No Tanks"
#    URL = "notanks"
#    weight = 1

#[[menu.main]]
#name = "course"
#URL = "course"
#weight = 2

#[[menu.main]]
#weight = 3
#name = "Pages"
#hasChildren = true
#
#  [[menu.main]]
#  parent = "Pages"
#  name = "teacher"
#  URL = "teacher"
#
#  [[menu.main]]
#  parent = "Pages"
#  name = "notice"
#  URL = "notice"
#
#  [[menu.main]]
#  parent = "Pages"
#  name = "event"
#  URL = "event"
#
#  [[menu.main]]
#  parent = "Pages"
#  name = "scholarship"
#  URL = "scholarship"
#
#  [[menu.main]]
#  parent = "Pages"
#  name = "research"
#  URL = "research"
#  
#[[menu.main]]
#name = "blog"
#URL = "blog"
#weight = 4
  
#[[menu.main]]
#name = "Contact"
#URL = "contact"
#weight = 5


# footer menu

[[menu.footer]]
name = "About Us"
URL = "about"

[[menu.footer]]
name = "How to Vote"
URL = "how-to-vote"

[[menu.footer]]
name = "Candidates"
URL = "candidates"

#[[menu.footer]]
#name = "scholarship"
#URL = "scholarship"
#
#[[menu.footer]]
#name = "research"
#URL = "research"


#################### default parameters ################################
[params]
logo = "images/logo_dark_transparent_200x68.png"
# Meta data
description = "Appreciating Oakland City Meetings"
author = "astropuffin"
# contact info
#address = "9567 Turner Trace Apt. BC C3G8A4"
#mobile = "+211234565523"
#mobile = "N/A"
email = "oakmtg-club@googlegroups.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-179247089-1" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

## Subscription
#[params.subscription]
#enable = true
## mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
#[params.map]
#enable = true
##TODO: add a more recent key
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
#map_latitude = "51.5223477"
#map_longitude = "-0.1622023"
#map_marker = "images/marker.png" # marker size 37*55 px
  
############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/search?q=%23oakmtg"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/astropuffin/oakmtg.club"

[[params.social]]
title = "email"
icon = "ti-email" # themify icon : https://themify.me/themify-icons
link = "mailto:oakmtg-club@googlegroups.com"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### French language #####################################
#[Languages.fr]
#languageName = "Fr"
#languageCode = "fr-fr"
#contentDir = "content/french"
#weight = 2
#home = "Accueil"
## copyright
#copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
